feuerwehren_tiles:
  path: '/_tiles/{z}/{x}/{y}.{format}'
  controller: \Schmid\Feuerwehren\Controller\TileController::tile
  requirements:
    z: \d+
    x: \d+
    y: \d+
    format: png|jpg
  defaults:
    format: png

feuerwehren_vt:
  path: '/_vt/{z}/{x}/{y}.pbf'
  controller: 'Schmid\\Feuerwehren\\Controller\\VectorTileController::pbfAction'
  requirements:
    z: '\d+'
    x: '\d+'
    y: '\d+'
  methods: [GET]
  access: 'public'