services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Schmid\Feuerwehren\:
    resource: '../Classes/*'

  Schmid\Feuerwehren\Command\TilesPrefetchCommand:
    arguments: [ ]
    tags:
      - name: 'console.command'
        command: 'feuerwehren:tiles:prefetch'
        description: 'Prefetch XYZ tiles into var/tiles for a given BBOX and zoom levels'

  # Middleware muss public sein (wird vom Core instanziert)
  Schmid\Feuerwehren\Middleware\ApiGatewayMiddleware:
    public: true