services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Schmid\Feuerwehren\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Schmid\Feuerwehren\Command\TilesPrefetchCommand:
    arguments: [ ]
    tags:
      - name: 'console.command'
        command: 'feuerwehren:tiles:prefetch'
        description: 'Prefetch XYZ tiles into var/tiles for a given BBOX and zoom levels'

  # Middleware muss public sein (wird vom Core instanziert)
  Schmid\Feuerwehren\Middleware\ApiGatewayMiddleware:
    public: true

  Schmid\Feuerwehren\Controller\PersonController:
    public: true

  Schmid\Feuerwehren\Controller\FeuerwehrController:
    public: true

  Schmid\Feuerwehren\Controller\JubilaeumController:
    public: true
    arguments:
      $feuerwehrRepository: '@Schmid\Feuerwehren\Domain\Repository\FeuerwehrRepository' # Hinzufügen

  Schmid\Feuerwehren\Controller\VectorTileController:
    public: true