http:
  middlewares:
    vite-cors:
      headers:
        accessControlAllowMethods:
          - "GET"
          - "OPTIONS"
          - "POST"
        accessControlAllowHeaders:
          - "*"
        accessControlAllowOriginList:
          - "*"
        accessControlMaxAge: 100
        addVaryHeader: true
