base: 'https://www.kfv-freising.de/'
baseVariants:
  -
    base: 'https://staging.kfv-freising.de/'
    condition: 'applicationContext == "Production/Staging"'
  -
    base: 'https://kfv-freising.ddev.site/'
    condition: 'applicationContext == "Development"'
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    locale: de_DE
    navigationTitle: Deutsch
    flag: de
    hreflang: ''
    websiteTitle: ''
rootPageId: 1
websiteTitle: ''
