#! /bin/bash

# coloring https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color


# TODO: check if this is the live branch

git add --all
git status

printf "\n${RED}First: check above if git added all your files.${NC}\n"

printf "\n${GREEN}GIT COMMIT: Tell me what you did? (type b or n or  CTRL + C for break if not all files added) ${NC}\n"
read git_commit_statement

if [ "$git_commit_statement" = "b" ]
    then
        printf "\nOK, deployment stopped. \n"
        exit
fi
if [ "$git_commit_statement" = "n" ]
    then
        printf "\nOK, deployment stopped. \n"
        exit
fi

# check if project vars are set
if [ -z "$git_commit_statement" ]
then
      printf "${RED}git commit statement is empty. Can not deploy. Deployment stopped.${NC}\n"
      exit;
fi

printf "\nOK, lets go on...\n"

git_branch=$(git branch | sed -n '/\* /s///p')

printf "\nGIT BRANCH: $git_branch \n"

git commit -m "$git_commit_statement"

printf "\n${GREEN}git pull... ${NC}\n"
git pull origin $git_branch

printf "\n${GREEN}git push... ${NC}\n"
git push origin $git_branch


printf "\n${GREEN}Finish. ${NC}\n"
