#! /bin/bash

# project vars
USERNAME=$(grep PRODUCTION_SSH_USER ./.ddev/config.yaml | cut -d '=' -f 2-)
REMOTESERVER=$(grep PRODUCTION_SSH_HOST ./.ddev/config.yaml | cut -d '=' -f 2-)
SSH_PATH_TO_TYPO3=$(grep PRODUCTION_SSH_ROOT_PATH ./.ddev/config.yaml | cut -d '=' -f 2-)
SSH_PATH_TO_TYPO3=$(grep PRODUCTION_SSH_ROOT_PATH ./.ddev/config.yaml | cut -d '=' -f 2-)
PRODUCTION_SSH_IS_COMPOSER_INSTALLATION=$(grep PRODUCTION_SSH_IS_COMPOSER_INSTALLATION ./.ddev/config.yaml | cut -d '=' -f 2-)

# standards
db_dump_name="db-dump.sql"
file_dump_name="file-dump.tar.gz"

# coloring https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# check if project vars are set
if [ -z "$USERNAME" ]
then
      printf "${RED}\$USERNAME is empty. Can not synchronize.${NC}\n"
      exit;
fi

if [ -z "$REMOTESERVER" ]
then
      printf "${RED}\$REMOTESERVER is empty. Can not synchronize.${NC}\n"
      exit;
fi

# START WORKING

printf "${GREEN}Make a new backup from live system.${NC}\n"

DIR=_BACKUP
if [[ -d "$DIR" ]];
then
    cd $DIR
    rm -rf *
    cd ..
else
    mkdir $DIR
fi


pathToLocalConfiguration="${SSH_PATH_TO_TYPO3}/public/typo3conf"
if [ "$PRODUCTION_SSH_IS_COMPOSER_INSTALLATION" = "0" ]
then
    pathToLocalConfiguration="${SSH_PATH_TO_TYPO3}/typo3conf"
fi

printf "${GREEN}Database backup...${NC}\n"

ssh ${USERNAME}@${REMOTESERVER} "cd ${pathToLocalConfiguration} && \
    db_user=\"\$(php -r '\$test = include(\"LocalConfiguration.php\"); print \$test[\"DB\"][\"Connections\"][\"Default\"][\"user\"];')\" && \
    db_password=\"\$(php -r '\$test = include(\"LocalConfiguration.php\"); print \$test[\"DB\"][\"Connections\"][\"Default\"][\"password\"];')\" && \
    db_hostname=\"\$(php -r '\$test = include(\"LocalConfiguration.php\"); print \$test[\"DB\"][\"Connections\"][\"Default\"][\"host\"];')\" && \
    db_name=\"\$(php -r '\$test = include(\"LocalConfiguration.php\"); print \$test[\"DB\"][\"Connections\"][\"Default\"][\"dbname\"];')\" && \
    mysqldump --opt --no-tablespaces -u\"\$db_user\" -p\"\$db_password\" -h\"\$db_hostname\" \$db_name | gzip -9 -c" > _BACKUP/db.sql.gz


printf "${GREEN}DB dump download finished.${NC}\n"

printf "${GREEN}Files download...${NC}\n"

[[ "${SSH_PATH_TO_TYPO3}" != */ ]] && SSH_PATH_TO_TYPO3="${SSH_PATH_TO_TYPO3}/"

pathToFileadmin="${SSH_PATH_TO_TYPO3}public/fileadmin"
if [ "$PRODUCTION_SSH_IS_COMPOSER_INSTALLATION" = "0" ]
then
    pathToFileadmin="${SSH_PATH_TO_TYPO3}fileadmin"
fi

rsync -hrPt --exclude={'_processed_/*','_temp_/*','user_upload/_temp_/*'} --delete -e ssh $USERNAME@$REMOTESERVER:$pathToFileadmin ./_BACKUP/

cd _BACKUP

tar -czvf fileadmin.tar.gz fileadmin

cd fileadmin
rm -rf *
rm -rf .*
cd ..
rmdir fileadmin

cd ..
