name: sitepackage/heroslider
typeName: heroslider
group: default
prefixFields: true
prefixType: full
basics:
  - TYPO3/Appearance
fields:
  -
    identifier: header
    useExistingField: true
  -
    identifier: slides
    type: Collection
    labelField: title
    maxitems: 5
    minitems: 1
    appearance:
      collapseAll: true
      levelLinksPosition: bottom
    fields:
      - identifier: title
        type: Text
      - identifier: image
        type: File
        minitems: 1
        maxitems: 1
      - identifier: bodytext
        type: Textarea
        enableRichtext: true
