settings:
  feuerwehren:
    api:
      allowedOrigins:
        - 'https://www.kfv-freising.de'
        - 'https://staging.kfv-freising.de'
        - 'https://kfv-freising.ddev.site'
    bbox:
      west: 11.3
      south: 48.3
      east: 12.08
      north: 48.7
    tileSource: mbtiles
    mbtilesPath: fileadmin/tiles/osm.mbtiles
    proxyUrl: https://a.tile.openstreetmap.org/{z}/{x}/{y}.png
    mbtilesUrl: ""
    vectorTiles:
      enabled: true
      mbtilesPath: fileadmin/tiles/oberbayern-vt.mbtiles