name: sitepackage/card-group
typeName: card-group
group: default
prefixFields: true
prefixType: full
basics:
  - TYPO3/Appearance
fields:
  -
    identifier: header
    useExistingField: true
  -
    identifier: color
    type: Select
    useExistingField: true
    renderType: selectSingle
  -
    identifier: sitepackage/breakpoints
    type: Basic
  -
    identifier: items
    type: Collection
    labelField: header
    minitems: 1
    appearance:
      collapseAll: true
      levelLinksPosition: bottom
    fields:
      - identifier: header
        type: Text
      - identifier: image
        type: File
        label: Bild
        maxitems: 1
      - identifier: bodytext
        type: Textarea
        enableRichtext: true
